# Generated by Django 4.1.5 on 2023-10-14 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IVRLeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('dial_dt', models.DateTimeField(auto_now=True, null=True)),
                ('call_status', models.CharField(max_length=40, null=True)),
                ('ivr_number', models.CharField(blank=True, max_length=20, null=True)),
                ('lead_forkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.leaddetails')),
            ],
        ),
        migrations.CreateModel(
            name='IVRLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=20, null=True)),
                ('case_status', models.CharField(max_length=30, null=True)),
                ('ivr_no', models.CharField(max_length=30, null=True)),
                ('lead_forkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.leaddetails')),
            ],
        ),
        migrations.CreateModel(
            name='IVR_LogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('call_status', models.CharField(max_length=40, null=True)),
                ('ivr_number', models.CharField(blank=True, max_length=20, null=True)),
                ('dtmf', models.CharField(blank=True, max_length=10, null=True)),
                ('dt', models.DateTimeField(auto_now=True, null=True)),
                ('callid', models.CharField(blank=True, max_length=50, null=True)),
                ('dst', models.CharField(max_length=40, null=True)),
                ('dsttech', models.CharField(max_length=40, null=True)),
                ('lead_forkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.leaddetails')),
            ],
        ),
    ]
