# Generated by Django 4.1.5 on 2023-10-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_ivrleadstatus_ivrleads_ivr_logdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='dtmf',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
