# Generated by Django 4.1.5 on 2023-10-19 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_callrecording_dtmf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecording',
            name='dtmf',
        ),
        migrations.AddField(
            model_name='queuedetails',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='UserExtendedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_status', models.CharField(blank=True, max_length=2, null=True)),
                ('extension_pause_status', models.CharField(blank=True, max_length=2, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictiveLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=20, null=True)),
                ('case_status', models.CharField(max_length=30, null=True)),
                ('lead_forkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.leaddetails')),
            ],
        ),
        migrations.CreateModel(
            name='PredictiveDialedCaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('dial_dt', models.DateTimeField(auto_now=True, null=True)),
                ('call_status', models.CharField(max_length=40, null=True)),
                ('lead_forkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.leaddetails')),
            ],
        ),
    ]
