# Generated by Django 4.1.5 on 2023-10-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_callrecording_dtmf_queuedetails_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='dtmf',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
