# Generated by Django 4.1.5 on 2023-10-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_callrecording_dtmf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valid_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('token', models.CharField(blank=True, max_length=400, null=True)),
                ('userid', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
